title: Leaderboard
theme: "minima"
baseurl: "/Leaderboard"
excerpt_separator: <!--more-->

collections:
  weekly:
    output: true
    # permalink:
  daily:
    output: true
  hourly:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      author: "feildmaster"

github:
  sponsor: feildmaster
