name: Daily Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *" # About 1 hour before reset
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: npm install
      - name: Update
        run: npm start daily
      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore: Daily Update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

